// Code generated by counterfeiter. DO NOT EDIT.
package mocks

import (
	"sync"

	"github.com/bborbe/sentry-proxy/pkg"
)

type Metrics struct {
	KafkaPublishDroppedIncStub        func()
	kafkaPublishDroppedIncMutex       sync.RWMutex
	kafkaPublishDroppedIncArgsForCall []struct {
	}
	KafkaPublishFailureIncStub        func()
	kafkaPublishFailureIncMutex       sync.RWMutex
	kafkaPublishFailureIncArgsForCall []struct {
	}
	KafkaPublishSuccessIncStub        func()
	kafkaPublishSuccessIncMutex       sync.RWMutex
	kafkaPublishSuccessIncArgsForCall []struct {
	}
	SentryAlertForwardIncStub        func()
	sentryAlertForwardIncMutex       sync.RWMutex
	sentryAlertForwardIncArgsForCall []struct {
	}
	SentryAlertRejectedIncStub        func()
	sentryAlertRejectedIncMutex       sync.RWMutex
	sentryAlertRejectedIncArgsForCall []struct {
	}
	SentryAlertTotalIncStub        func()
	sentryAlertTotalIncMutex       sync.RWMutex
	sentryAlertTotalIncArgsForCall []struct {
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *Metrics) KafkaPublishDroppedInc() {
	fake.kafkaPublishDroppedIncMutex.Lock()
	fake.kafkaPublishDroppedIncArgsForCall = append(fake.kafkaPublishDroppedIncArgsForCall, struct {
	}{})
	stub := fake.KafkaPublishDroppedIncStub
	fake.recordInvocation("KafkaPublishDroppedInc", []interface{}{})
	fake.kafkaPublishDroppedIncMutex.Unlock()
	if stub != nil {
		fake.KafkaPublishDroppedIncStub()
	}
}

func (fake *Metrics) KafkaPublishDroppedIncCallCount() int {
	fake.kafkaPublishDroppedIncMutex.RLock()
	defer fake.kafkaPublishDroppedIncMutex.RUnlock()
	return len(fake.kafkaPublishDroppedIncArgsForCall)
}

func (fake *Metrics) KafkaPublishDroppedIncCalls(stub func()) {
	fake.kafkaPublishDroppedIncMutex.Lock()
	defer fake.kafkaPublishDroppedIncMutex.Unlock()
	fake.KafkaPublishDroppedIncStub = stub
}

func (fake *Metrics) KafkaPublishFailureInc() {
	fake.kafkaPublishFailureIncMutex.Lock()
	fake.kafkaPublishFailureIncArgsForCall = append(fake.kafkaPublishFailureIncArgsForCall, struct {
	}{})
	stub := fake.KafkaPublishFailureIncStub
	fake.recordInvocation("KafkaPublishFailureInc", []interface{}{})
	fake.kafkaPublishFailureIncMutex.Unlock()
	if stub != nil {
		fake.KafkaPublishFailureIncStub()
	}
}

func (fake *Metrics) KafkaPublishFailureIncCallCount() int {
	fake.kafkaPublishFailureIncMutex.RLock()
	defer fake.kafkaPublishFailureIncMutex.RUnlock()
	return len(fake.kafkaPublishFailureIncArgsForCall)
}

func (fake *Metrics) KafkaPublishFailureIncCalls(stub func()) {
	fake.kafkaPublishFailureIncMutex.Lock()
	defer fake.kafkaPublishFailureIncMutex.Unlock()
	fake.KafkaPublishFailureIncStub = stub
}

func (fake *Metrics) KafkaPublishSuccessInc() {
	fake.kafkaPublishSuccessIncMutex.Lock()
	fake.kafkaPublishSuccessIncArgsForCall = append(fake.kafkaPublishSuccessIncArgsForCall, struct {
	}{})
	stub := fake.KafkaPublishSuccessIncStub
	fake.recordInvocation("KafkaPublishSuccessInc", []interface{}{})
	fake.kafkaPublishSuccessIncMutex.Unlock()
	if stub != nil {
		fake.KafkaPublishSuccessIncStub()
	}
}

func (fake *Metrics) KafkaPublishSuccessIncCallCount() int {
	fake.kafkaPublishSuccessIncMutex.RLock()
	defer fake.kafkaPublishSuccessIncMutex.RUnlock()
	return len(fake.kafkaPublishSuccessIncArgsForCall)
}

func (fake *Metrics) KafkaPublishSuccessIncCalls(stub func()) {
	fake.kafkaPublishSuccessIncMutex.Lock()
	defer fake.kafkaPublishSuccessIncMutex.Unlock()
	fake.KafkaPublishSuccessIncStub = stub
}

func (fake *Metrics) SentryAlertForwardInc() {
	fake.sentryAlertForwardIncMutex.Lock()
	fake.sentryAlertForwardIncArgsForCall = append(fake.sentryAlertForwardIncArgsForCall, struct {
	}{})
	stub := fake.SentryAlertForwardIncStub
	fake.recordInvocation("SentryAlertForwardInc", []interface{}{})
	fake.sentryAlertForwardIncMutex.Unlock()
	if stub != nil {
		fake.SentryAlertForwardIncStub()
	}
}

func (fake *Metrics) SentryAlertForwardIncCallCount() int {
	fake.sentryAlertForwardIncMutex.RLock()
	defer fake.sentryAlertForwardIncMutex.RUnlock()
	return len(fake.sentryAlertForwardIncArgsForCall)
}

func (fake *Metrics) SentryAlertForwardIncCalls(stub func()) {
	fake.sentryAlertForwardIncMutex.Lock()
	defer fake.sentryAlertForwardIncMutex.Unlock()
	fake.SentryAlertForwardIncStub = stub
}

func (fake *Metrics) SentryAlertRejectedInc() {
	fake.sentryAlertRejectedIncMutex.Lock()
	fake.sentryAlertRejectedIncArgsForCall = append(fake.sentryAlertRejectedIncArgsForCall, struct {
	}{})
	stub := fake.SentryAlertRejectedIncStub
	fake.recordInvocation("SentryAlertRejectedInc", []interface{}{})
	fake.sentryAlertRejectedIncMutex.Unlock()
	if stub != nil {
		fake.SentryAlertRejectedIncStub()
	}
}

func (fake *Metrics) SentryAlertRejectedIncCallCount() int {
	fake.sentryAlertRejectedIncMutex.RLock()
	defer fake.sentryAlertRejectedIncMutex.RUnlock()
	return len(fake.sentryAlertRejectedIncArgsForCall)
}

func (fake *Metrics) SentryAlertRejectedIncCalls(stub func()) {
	fake.sentryAlertRejectedIncMutex.Lock()
	defer fake.sentryAlertRejectedIncMutex.Unlock()
	fake.SentryAlertRejectedIncStub = stub
}

func (fake *Metrics) SentryAlertTotalInc() {
	fake.sentryAlertTotalIncMutex.Lock()
	fake.sentryAlertTotalIncArgsForCall = append(fake.sentryAlertTotalIncArgsForCall, struct {
	}{})
	stub := fake.SentryAlertTotalIncStub
	fake.recordInvocation("SentryAlertTotalInc", []interface{}{})
	fake.sentryAlertTotalIncMutex.Unlock()
	if stub != nil {
		fake.SentryAlertTotalIncStub()
	}
}

func (fake *Metrics) SentryAlertTotalIncCallCount() int {
	fake.sentryAlertTotalIncMutex.RLock()
	defer fake.sentryAlertTotalIncMutex.RUnlock()
	return len(fake.sentryAlertTotalIncArgsForCall)
}

func (fake *Metrics) SentryAlertTotalIncCalls(stub func()) {
	fake.sentryAlertTotalIncMutex.Lock()
	defer fake.sentryAlertTotalIncMutex.Unlock()
	fake.SentryAlertTotalIncStub = stub
}

func (fake *Metrics) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *Metrics) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ pkg.Metrics = new(Metrics)
